app/blueprints/shop/models.py
from app import db
from datetime import datetime as dt
from app.blueprints.authentication.models import User


class StripeProduct(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    stripe_product_id = db.Column(db.String)
    name = db.Column(db.String)
    image = db.Column(db.String)
    description = db.Column(db.Text)
    price = db.Column(db.Integer)
    tax = db.Column(db.Integer)
    date_created = db.Column(db.DateTime, default=dt.utcnow)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'<Product: {self.name} @{self.price}>'


class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    image = db.Column(db.String)
    description = db.Column(db.Text)
    price = db.Column(db.Float)
    tax = db.Column(db.Float)
    date_created = db.Column(db.DateTime, default=dt.utcnow)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'<Product: {self.name} @{self.price}>'

class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    product = db.Column(db.String, nullable=False)
    date_added = db.Column(db.DateTime, default=dt.utcnow)

    def to_dict(self):
        data = {
            'product': StripeProduct.query.filter_by(stripe_product_id=self.product).first(),
            'user': User.query.get(self.user_id),
        }
        return data

    def save(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'<Product: {self.user_id} | {self.product}>'

class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    product_id = db.Column(db.ForeignKey('product.id'), nullable=False)
    date_filled = db.Column(db.DateTime, default=dt.utcnow)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'<Product: {self.user_id} | {self.product_id}>'

app/blueprints/shop/__init__.py
from flask import Blueprint

bp = Blueprint('shop', __name__, url_prefix='/shop')

<<<<<<< HEAD
from .import routes
=======
from .import routes, models
>>>>>>> d73017b5cc20016d4a5fb5cbe944b665f3696e16

app/blueprints/shop/routes.py
from time import strptime
from flask.helpers import url_for
from .import bp as app
from flask import json, render_template, redirect, flash, request, session, current_app, jsonify
from .models import Product, Cart, StripeProduct
from flask_login import current_user
import stripe
from app import db
import pprint

@app.route('/')
def index():
    """
    [GET] /shop
    """
    stripe.api_key = current_app.config.get('STRIPE_SECRET_KEY')
    # print(stripe.Product.list())
    # print(stripe.Price.retrieve('price_1JCnOKInbeNyBE8aEngKCetu'))
    context = {
        'products': StripeProduct.query.all()
    }
    print(StripeProduct.query.all())
    return render_template('shop/index.html', **context)

@app.route('/cart', methods=['GET', 'POST'])
def cart():
    """
    [GET] /shop/cart
    """
    from app.context_processors import build_cart
    display_cart = build_cart()['cart_dict']
    session['session_display_cart'] = display_cart
    if request.method == 'POST':
        # Clear the current user's cart to make way for the new objects
        display_cart = build_cart()['cart_dict']
        session['session_display_cart'] = display_cart
        [db.session.delete(i) for i in Cart.query.filter_by(user_id=current_user.id).all()]
        # reset the sequence for the cart IDs for the newly added cart objects
        db.session.execute('ALTER SEQUENCE cart_id_seq RESTART WITH 1;')
        db.session.commit()
        for idx, new_amount in enumerate(request.form.getlist('amount')):
            curr_obj_id = list(display_cart.values())[idx]['product_id']
            # get the matching object and create copies to add to the cart
            for _ in range(int(new_amount)):
                Cart(user_id=current_user.id, product=curr_obj_id).save()
        flash('Updated quantities', 'info')
        return redirect(url_for('shop.cart'))
    context = {
        'cart': display_cart.values()
    }
    #pprint.pprint(display_cart.values())

    if not current_user.is_authenticated:
        flash('You must login to view your cart', 'warning')
        return redirect(url_for('authentication.login'))
    return render_template('shop/cart.html', **context)

@app.route('/cart/add')
def add_to_cart():
    """
    [GET] /shop/cart/add
    """
    if not current_user.is_authenticated:
        flash('You must login to add items to your cart', 'warning')
        return redirect(url_for('authentication.login'))

    # Make a new product
    product = StripeProduct.query.get(request.args.get('id'))

    # Save it to their cart
    Cart(user_id=current_user.id, product=product.stripe_product_id).save()
    flash(f'You have added {product.name} to the cart', 'success')
    return redirect(url_for('shop.index'))

@app.route('/cart/remove')
def remove_from_cart():
    if not current_user.is_authenticated:
        flash('You must login to remove items from your cart', 'warning')
        return redirect(url_for('authentication.login'))
    [db.session.delete(i) for i in Cart.query.filter_by(product=request.args.get('product_id')).all()]
    db.session.commit()
    product_name = StripeProduct.query.filter_by(stripe_product_id=request.args.get('product_id')).first().name
    flash(f'Removed {product_name}', 'info')
    return redirect(url_for('shop.cart'))

@app.route('/success')
def shop_success():
    pass

@app.route('/failure')
def shop_failure():
    pass

@app.route('/checkout', methods=['POST'])
def checkout():
    stripe.api_key = current_app.config.get('STRIPE_SECRET_KEY')
    dc = session.get('session_display_cart')
    
    l_items = []
    for product in dc.values():
        product_dict = {
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                        'name': product['name'],
                        'images': [product['image']]
                    },
                    'unit_amount': int(float(product['price']) * 100),
                },
                'quantity': product['quantity'],
            }
        l_items.append(product_dict)

    try:
        # Handle payment
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=l_items,
            mode='payment',
            success_url='http://localhost:5000/shop/cart',
            cancel_url='http://localhost:5000/shop/cart',
        )

        # Clear all items from cart
        [db.session.delete(i) for i in Cart.query.filter_by(user_id=current_user.id).all()]
        db.session.commit()

        flash('Your order was processed successfully', 'primary')
        return jsonify({ 'session_id': checkout_session.id })
    except Exception as e:
        return jsonify(error=str(e)), 403

@app.route('/seed')
def seed_stripe_products():
    stripe.api_key = current_app.config.get('STRIPE_SECRET_KEY')

    def seed_data():
        # print(stripe.Product.list().get('data'))
        list_to_store_in_db = []

        # Clear all items from database
        [db.session.delete(i) for i in StripeProduct.query.all()]
        db.session.commit()

        for p in stripe.Product.list().get('data'):
            list_to_store_in_db.append(StripeProduct(stripe_product_id=p['id'], name=p['name'], image=p['images'][0], description=p['description'], price=int(float(p['metadata']['price']) * 100), tax=int(float(p['metadata']['tax']) * 100)))
        
        db.session.add_all(list_to_store_in_db)
        db.session.commit()

    seed_data()
    return jsonify({ 'message': 'Success' })

app/templates/shop/cart.html
{% extends 'layout.html' %}
​
{% block content %}
<h3>Cart</h3>
<hr>
​
<div class="card shopping-cart">
    <div class="card-header bg-dark text-light">
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        Shopping Cart
        <a href="{{ url_for('shop.index') }}" class="btn btn-outline-info btn-sm pull-right">Continue Shopping</a>
        <div class="clearfix"></div>
    </div>
    <form action="{{ url_for('shop.cart') }}" method="POST">
        <div class="card-body">
            {% for p in cart %}
            <!-- PRODUCT -->
            <div class="row">
                <div class="col-12 col-sm-12 col-md-2 text-center">
                    <img class="img-responsive" src="{{ p.image }}" alt="prewiew" width="120" height="80">
                </div>
                <div class="col-12 text-center col-sm-12 text-md-left col-md-6">
                    <h4 class="product-name"><strong>{{ p.name }}</strong></h4>
                    <h4>
                        <small>{{ p.description }}</small>
                    </h4>
                </div>
                <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row no-padding">
                    <div class="col-6 col-sm-6 col-md-6 text-md-right" style="padding-top: 5px">
                        <h6><strong>{{ "$%.2f"|format(p.price / 100) }} <span class="text-muted">x</span></strong></h6>
                    </div>
                    <div class="col-4 col-sm-4 col-md-4">
                        <div class="quantity">
                            <input type="number" name="amount" step="1" max="99" min="1" value="{{ p.quantity }}" title="Qty" class="qty"
                                size="4">
                        </div>
                    </div>
                    <div class="col-2 col-sm-2 col-md-2 no-padding">
                        <a class="remove-button btn btn-danger btn-block" href="{{ url_for('shop.remove_from_cart', product_id=p.product_id) }}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="currentColor" class="bi bi-trash"
                            viewBox="0 0 16 16">
                            <path
                                d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                            <path fill-rule="evenodd"
                                d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                        </svg>
                    </a>
                    </div>
                </div>
            </div>
            <hr>
            <!-- END PRODUCT -->
            {% endfor %}
            <div class="pull-right">
                <input type="submit" class="btn btn-outline-secondary pull-right" value="Update Shopping Cart" />
            </div>
        </div>
    </form>
    <div class="card-footer">
        <!-- <div class="coupon col-md-5 col-sm-5 no-padding-left pull-left">
                <div class="row">
                    <div class="col-6">
                        <input type="text" class="form-control" placeholder="cupone code">
                    </div>
                    <div class="col-6">
                        <input type="submit" class="btn btn-default" value="Use cupone">
                    </div>
                </div>
            </div> -->
        <div class="text-right">
            <div class="cart-totals">
                Subtotal: <b>{{ "$%.2f"|format(cart_subtotal / 100) }}</b>
            </div>
            <div class="cart-totals">
                Tax: <b>{{ "$%.2f"|format(cart_tax / 100) }}</b>
            </div>
            <div class="cart-totals">
                Grand total: <b>{{ "$%.2f"|format(cart_grandtotal / 100) }}</b>
            </div>
        </div>
        <div class="pull-right" style="margin: 10px">
            <form id="checkout-form" action="{{ url_for('shop.checkout') }}" method="POST">
                <input type="submit" class="btn btn-success pull-right" value="Checkout" />
            </form>
        </div>
    </div>
</div>

{% endblock content %}
​
{% block scripts %}
{{ super() }}
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="https://js.stripe.com/v3/"></script>
​
<script>
    var stripe = Stripe('{{ STRIPE_PUBLISHABLE_KEY }}')

    $('#checkout-form').on('submit', function (e) {
        e.preventDefault();
        fetch('{{ url_for("shop.checkout") }}', {
            'method': 'POST',
            'mode': 'cors',
            'headers': {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ 'message': 'This works' })
        })
            .then(res => res.json())
            .then(data => { console.log(data); stripe.redirectToCheckout({ sessionId: data['session_id'] }) })
    })
</script>
{% endblock scripts %}

app/templates/shop/index.html
{% extends 'layout.html' %}
​
{% block content %}
<h3>Shop</h3>
<hr>
​
<div class="card-deck">
    {% for p in products %}
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h6>
                    {{ p.name }}
                    <span class="float-right">${{ '{:,.2f}'.format(p.price / 100) }}</span>
                </h6>
            </div>
            <div class="card-body">
                <img class="card-img-top" src="{{ p.image }}" alt="{{ p.name }}">
                <a class="btn btn-success btn-block" style="margin-top: 10px;"
                    href="{{ url_for('shop.add_to_cart', id=p.id) }}">Add to cart</a>
                <p class="card-text" style="margin-top: 10px;">{{ p.description }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}