app/blueprints/blog/models.py
from app import db
from datetime import datetime as dt

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    date_created = db.Column(db.DateTime, default=dt.utcnow)
    date_updated = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'<Post: {self.body[:30]}>'

app/blueprints/blog/__init__.py
from flask import Blueprint

bp = Blueprint('blog', __name__, url_prefix='/blog')

<<<<<<< HEAD
from .import routes
=======
from .import routes, models
>>>>>>> d73017b5cc20016d4a5fb5cbe944b665f3696e16

app/blueprints/blog/routes.py
from flask import render_template, url_for
from werkzeug.utils import redirect
from app.blueprints.blog.models import Post
from .import bp as app
from flask import flash, request
from flask_login import current_user, login_required

@app.route('/post/<int:id>')
@login_required
def get_post(id):
    context = {
        'p': Post.query.get(id)
    }
    return render_template('blog-single.html', **context)
<<<<<<< HEAD
=======

@app.route('/post/create', methods=['POST'])
@login_required
def create_post():
    Post(body=request.form.get('body'), user_id=current_user.id).save()
    flash('Post created successfully', 'primary')
    return redirect(url_for('main.home'))
>>>>>>> d73017b5cc20016d4a5fb5cbe944b665f3696e16

app/templates/blog-single.html
{% extends 'layout.html' %}
<<<<<<< HEAD
{% block content %}
<h3>Single Blog Post</h3>
<hr />
<a href="{{ url_for('main.home') }}" class="btn btn-info">Back</a>
<li class="list-group-item">
    <p>
        {{ p['body'] }}
    </p>
    <div>
        <span>
            <cite>&mdash; {{ p.author }}</cite>
            <small class="float-right">{{ p.timestamp }}</small>
        </span>
        ​
    </div>
</li>
=======

{% block content %}
    <h3>Single Blog Post</h3>
    <hr />

    <a class="btn btn-info" href="{{ url_for('main.home') }}">Back</a>

    <li class="list-group-item">
        <p>{{ p['body'] }}</p>
        <div>
            <span>
                <cite>&mdash; {{ p.author.first_name }} {{ p.author.last_name }}</cite>
                <small class="float-right">{{ moment(p.date_created).fromNow() }}</small>
            </span>
    
        </div>
    </li>
>>>>>>> 11cfe8ba5f502b36ad55db0f81c29ef2adf3c938

{% endblock content %}

app/templates/blog.html
<!doctype html>
<html lang="en">

<head>
    <title>Fakebook | Profile</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
                aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('get_profile') }}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('get_blog') }}">Blog</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">Shop</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownId">
                            <a class="dropdown-item" href="#">Products</a>
                            <a class="dropdown-item" href="#">Cart</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('get_contact') }}">Contact</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <main>
        <h3>Blog</h3>
        <hr />
        <p>This is my blog page</p>
    </main>
    <footer>
        
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/contact.html
{% extends 'layout.html' %}

{% block content %}
<<<<<<< HEAD
    <main>
        <h3>Contact</h3>
        <hr />
        <p>This is my contact info page</p>
    </main>
=======
<h3>
    Contact
</h3>
<hr />
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form action="{{ url_for('main.contact') }}" method="POST">
            <div class="form-group">
                <input type="email" class="form-control" name="email" placeholder="Email">
            </div>
            <div class="form-group">
              <select class="form-control" name="inquiry" id="">
                <option disabled selected>Please choose one option</option>
                <option value="cheap">Starting $500+</option>
                <option value="expensive">Starting $1,000+</option>
                <option value="luxury">Starting $5000+</option>
              </select>
            </div>
            <div class="form-group">
                <textarea class="form-control" name="message" id="" cols="30" rows="10"></textarea>
            </div>
            <button class="btn btn-info btn-block">Send us a message</button>
        </form>
    </div>
</div>
>>>>>>> d73017b5cc20016d4a5fb5cbe944b665f3696e16
{% endblock content %}

app/templates/home.html
{% extends 'layout.html' %}

{% block content %}

    <h3>
        Home
    </h3>
    <hr />

    <form action="{{ url_for('blog.create_post') }}" method="POST">
        <div class="form-group">
            <div class="row">
                <div class="col-md-10">
                    <input class="form-control" type="text" name='body' placeholder="Your blog post here..." />
                </div>
                <div class="col-md-2">
                    <input class="btn btn-info btn-block" type="submit" value="Post" />
                </div>
            </div>
        </div>
    </form>

    <hr />

    <ul class="list-group">
        {% for p in posts %}
        <li class="list-group-item">
            <p>
                <a href="{{ url_for('blog.get_post', id=p.id) }}">{{ p['body'] }}</a>
                {# <a href="/blog/{{ p.id }}">{{ p['body'] }}</a> #}
            </p>
            <div>
                <span>
                    <cite>&mdash; {{ p.author.first_name }} {{ p.author.last_name }}</cite>
                    <small class="float-right">{{ moment(p.date_created).fromNow() }}</small>
                </span>
        
            </div>
        </li>
        {% endfor %}
    </ul>


{% endblock content %}

app/templates/layout.html
<!doctype html>
<html lang="en">
    <head>
        <title>Fakebook | Profile</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    </head>
    <body>

        <header>
            {% include './includes/navigation.html' %}
        </header>

        <main class="container">

            {% with messages=get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for c, m in messages %}
                        <div class="alert alert-{{ c }} alert-dismissible fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <strong>{{ m }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}


            {% block content %}{% endblock content %}
        </main>

        <footer class="bg-dark text-light">
            {% include './includes/footer.html' %}
        </footer>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        {% block scripts %}
            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
            {{ moment.include_moment() }}
        {% endblock scripts %}
    </body>
</html>

app/templates/profile.html
{% extends 'layout.html' %}

{% block content %}
    <h3>
        Profile | Welcome {{ current_user.email }}
    </h3>
    <hr />
    
    <div class="row">   
        <div class="col-md-4">
            <img class="img-fluid" src="{{ current_user.image }}" alt="profile">
        </div>
        <div class="col-md">
            <form action="{{ url_for('main.profile') }}" method="POST" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="First Name" name="first_name" value="{{ current_user.first_name }}" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Last Name" name="last_name" value="{{ current_user.last_name }}" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="example@email.com" name="email" value="{{ current_user.email }}" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <input type="file" class="form-control-file" name="profile-image" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <textarea class="form-control" name="bio" id="" cols="30" rows="10" placeholder="Type bio here">{{ current_user.bio }}</textarea>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <input type="submit" class="btn btn-info btn-block" value="Update Profile" />
                    </div>
                </div>
            </form>
        </div>
    </div>
<<<<<<< HEAD
{% endblock content %}
=======

    <hr />

    <div class="row">
        <div class="col-md-12">
            <ul class="list-group">
                {% for p in posts %}
                <li class="list-group-item">
                    <p>
                        <a href="{{ url_for('blog.get_post', id=p.id) }}">{{ p['body'] }}</a>
                        {# <a href="/blog/{{ p.id }}">{{ p['body'] }}</a> #}
                    </p>
                    <div>
                        <span>
                            <cite>&mdash; {{ p.author.first_name }} {{ p.author.last_name }}</cite>
                            <small class="float-right">{{ moment(p.date_created).fromNow() }}</small>
                        </span>
            
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}
>>>>>>> d73017b5cc20016d4a5fb5cbe944b665f3696e16